name: Release

on:
  push:
    branches: [ master ]

jobs:
  linux:
    name: Build Debian Bookworm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure docker
        run:  |
          echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Package for Debian Bookworm
        run: |
          ./packaging/build package-docker bookworm-amd64 ..

      - name: Package for Ubuntu Jammy
        run: |
          ./packaging/build package-docker jammy-amd64 ..

      - name: Upload Packages to GitHub
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: targets/**/*.deb
          tag: "nightly"
          file_glob: true
          overwrite: true
